export const MOTIVATION_QUOTES = [
    "Bugün harika bir gün olacak.",
    "Her gün yeni bir başlangıçtır.",
    "Kendine inan, başarabilirsin.",
    "Küçük adımlar büyük değişimler yaratır.",
    "Asla pes etme.",
    "Zorluklar seni güçlendirir.",
    "Hayallerinin peşinden git.",
    "Bugünü dünden daha iyi yap.",
    "Sen sandığından daha güçlüsün.",
    "Başarı, her gün tekrarlanan küçük çabaların toplamıdır.",
    "Gülümse, hayat sana geri gülümser.",
    "Sadece başla.",
    "Engeller, başarıya giden yoldaki basamaklardır.",
    "Disiplin, hedefler ile başarı arasındaki köprüdür.",
    "Bugün kendin için bir şey yap.",
    "Yarınlar, bugün yaptıklarınla şekillenir.",
    "Kendini sev, kendine güven.",
    "Her anı değerlendir.",
    "Pozitif düşün, pozitif yaşa.",
    "Başarı bir yolculuktur, varış noktası değil.",
    "Hata yapmaktan korkma, öğrenmekten korkma.",
    "Güçlü ol, çünkü her şey düzelecek.",
    "Sabır, başarının anahtarıdır.",
    "Hayal edebiliyorsan, yapabilirsin.",
    "Sınırlarını zorla.",
    "En iyi yatırım kendine yaptığın yatırımdır.",
    "Vazgeçmediğin sürece yenilmiş sayılmazsın.",
    "Her zorluğun arkasında bir kolaylık vardır.",
    "Dünü değiştiremezsin ama bugünü ve yarını değiştirebilirsin.",
    "Odaklan ve ilerle.",
    "Başarı tesadüf değildir.",
    "Cesaret, korkuya rağmen devam etmektir.",
    "Kendini başkalarıyla kıyaslama, dünkü kendinle kıyasla.",
    "Mutluluk bir seçimdir.",
    "Şükretmek, bereketin anahtarıdır.",
    "Yıldızlara ulaşmak için ayakların yere basmalı.",
    "Hayat, sen planlar yaparken başına gelenlerdir.",
    "Büyük hayaller kur ve onlara ulaşmak için çalış.",
    "Zaman en değerli hazinedir, onu iyi kullan.",
    "Karanlığın en yoğun olduğu an, aydınlığın en yakın olduğu andır.",
    "Başlamak için mükemmel olmak zorunda değilsin, ama mükemmel olmak için başlamak zorundasın.",
    "Sadece inan.",
    "Her şey seninle başlar.",
    "Gelecek, bugünden hazırlananlara aittir.",
    "İmkansız diye bir şey yoktur, sadece zaman alır.",
    "Kendi hikayenin kahramanı sensin.",
    "Yetenek isabet ettirilemeyen hedefi vuran, deha ise görülemeyen hedefi vuran nişancıdır.",
    "Başarısızlık, daha zekice başlama fırsatıdır.",
    "Yapabileceğine inanıyorsan, yolun yarısını gitmişsin demektir.",
    "Mucizeler, inananların başına gelir.",
    "Bugün ektiğin tohumlar yarın çiçek açacak.",
    "Erteleme, harekete geç.",
    "Kendine bir şans ver.",
    "Hayat cesurları sever.",
    "Unutma, her fırtına diner.",
    "Kendi ışığını yak.",
    "Başkalarının ne dediği değil, senin ne hissettiğin önemli.",
    "Düşmek değil, kalkamamak sorundur.",
    "Hedefine kilitlen.",
    "Bugün, hayatının geri kalanının ilk günü.",
    "Sevgiyle yapılan her iş başarılır.",
    "Nefes al, ve yeniden dene.",
    "Her gün bir hediye.",
    "Azim ve kararlılıkla her şey mümkün.",
    "Hayallerin gerçeğe dönüşmeyi bekliyor.",
    "İyi şeyler zaman alır.",
    "Sakin ol ve planına sadık kal.",
    "Kendine karşı nazik ol.",
    "İçindeki gücü keşfet.",
    "Fırsatlar, onları görmeye hazır olanlara görünür.",
    "Sadece yap.",
    "Hayatı dolu dolu yaşa.",
    "Daha iyi bir sen için çalış.",
    "Geçmiş ders, gelecek umuttur.",
    "Zor zamanlar güçlü insanlar yaratır.",
    "Her gün %1 daha iyi ol.",
    "Başarı, cesaretin ödülüdür.",
    "Kendi yolunu çiz.",
    "Hayatın direksiyonuna geç.",
    "İçindeki sesi dinle.",
    "Tutkunu takip et.",
    "Yolun sonu değil, yolculuğun kendisi güzeldir.",
    "Bir gülümseme dünyayı değiştirebilir.",
    "Küçük mutlulukların tadını çıkar.",
    "Kendini olduğu gibi kabul et.",
    "Daima ileri bak.",
    "Harekete geçmek için bekleme.",
    "Sen bir mucizesin.",
    "Doğru zaman şimdidir.",
    "Potansiyelini açığa çıkar.",
    "Hayat yaşamaya değer.",
    "Umut her zaman vardır.",
    "Başarı senin ellerinde.",
    "Sadece ilerle.",
    "Güneşe yüzünü dön, gölgeler arkanda kalsın.",
    "Emeğinin karşılığını alacaksın.",
    "İyi niyetle başlanan her iş hayırla sonuçlanır.",
    "Her doğan güneş yeni bir umuttur.",
    "Kendin ol.",
    "Hayat bir macera, tadını çıkar."
];
